# Generated by Django 5.2.1 on 2025-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_device_devicedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('abort', 'Abort')], default='active', max_length=10),
        ),
    ]
