# Generated by Django 5.2.1 on 2025-06-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='device',
            name='switch',
            field=models.BooleanField(default=False),
        ),
    ]
